import { CheckBox, ListView, LineEdit, Palette, Button, StandardButton } from "std-widgets.slint";

export struct TodoItem {
  task: string,
  checked: bool,
}

export global AppConfig {
  in-out property<bool> dark-theme: true;
  out property<relative-font-size> font_size: 2rem;
  in property<[TodoItem]> todos: [];
}
  min-width: 600px;
  min-height: 600px;
  title: "2do-app";

  callback add_task_cb(string);

  VerticalLayout {
    padding: 15px;
    spacing: 5px;
    title_text := Text {
      title_text := Text {
        font-size: AppConfig.font_size;
        text: "Todos: ";
    }
    HorizontalLayout {
      search_task_in := LineEdit {
        accepted(task) => {
          root.add_task_cb(task);
        }
        placeholder-text: "Search task";
      }
      search_task_btn := Button {
        text: "Search";
      }
    }
    add_task_btn := Button {
      text: "Add task";
      clicked => {
      }
    }
    todo_list := ListView {
      for todo in AppConfig.todos: HorizontalLayout {
        CheckBox {
          toggled => {
            todo.checked = self.checked;
          }
          text: todo.task;
          checked: todo.checked;
        }
      }
    }
  }
}
