import { CheckBox, ListView, LineEdit, Palette, Button, StandardButton, Switch, TextEdit } from "std-widgets.slint";

export struct TodoItem {
  task: string,
  checked: bool,
}

export global AppConfig {
  in-out property<bool> dark-theme: true;
  out property<relative-font-size> font_size: 2rem;
  in property<[TodoItem]> todos: [];
}

export component AppWindow inherits Window {

  callback theme_init();
  callback add_task_cb(string);
  callback add_task_popup_show();
  min-width: 600px;
  min-height: 600px;
  title: "2do-app";

  theme_init => {
    Palette.color-scheme = AppConfig.dark-theme ? ColorScheme.dark : ColorScheme.light;
  }
  add_task_popup_show => {
    add_task_popup.show();
  }

  add_task_popup := PopupWindow {
    Rectangle {
      background: Palette.background;
      border-color: Palette.border;
      border-width: 1px;
      width: 100%;
      height: 100%;
    }
    TextEdit {
      text: "Sample";
    }
  }
  VerticalLayout {
    padding: 15px;
    spacing: 5px;
    HorizontalLayout {
      title_text := Text {
        font-size: AppConfig.font_size;
        text: "Todos: ";
      }
      Rectangle{} // Spacer
      Switch {
        text: "Dark theme";
        checked: AppConfig.dark-theme;
        toggled => {
          AppConfig.dark-theme = self.checked ? true : false;
          Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
        }
      }
    }
    HorizontalLayout {
      search_task_in := LineEdit {
        //width: 70%;
        accepted(task) => {}
        placeholder-text: "Search task";
      }
      Rectangle{
        width: 1%;
      } // Spacer
      search_task_btn := Button {
        text: "Search";
      }
    }
    add_task_btn := Button {
      text: "Add task";
      clicked => {
        root.add_task_popup_show();
      }
    }
    todo_list := ListView {
      for todo in AppConfig.todos: HorizontalLayout {
        CheckBox {
          toggled => {
            todo.checked = self.checked;
          }
          text: todo.task;
          checked: todo.checked;
        }
      }
    }
  }
}
