name: Deploy static content
on:
  push:
    branches: ['main']
    paths:
      - "2do-gui/**"
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
      branches: ['main']
      paths:
        - "2do-gui/**"

permissions:
  contents: read
  pages: write
  id-token: write # to verify the deployment originates from an appropriate source

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: |
          cd 2do-gui
          npm ci
      - name: Build
        run: |
          cd 2do-gui
          npm run build

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './2do-gui/dist/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
